theme: remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme 
title: "Herramientas de programación para la producción y difusión de estadísticas socioeconómicas - ASET"
description: ""
